[gc]commit

diff --git a/essay/publish b/essay/publish
--- a/essay/publish
+++ b/essay/publish
@@ -2,6 +2,11 @@
 
 # do publish
 emacs --batch --script publish.el
+if [ $? != 0 ]
+then
+    echo "publish failed"
+    exit 1
+fi
 ./addcode
 cd ../www/
 rm -rf images css
